language: php

php:
   - 7.0
   - 7.1
 
    
services:
    - postgresql
    - mysql
    


  
before_install:
     - mysql -e 'CREATE DATABASE IF NOT EXISTS notadd;'    
  
    
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer self-update
    - travis_retry composer install --no-interaction --prefer-source

before_script: 
    - git reset --hard HEAD
    - psql -c 'create database notadd;' -U postgres
    
script:    
    - php notadd integration:configuration —driver=pgsql —host=127.0.0.1 —port=5432 —database=notadd —username=postgres —password= —prefix=pre_; fi
    - php notadd integration


after_success:
    - bash <(curl -s https://codecov.io/bash) -t 4916eb3f-d129-4484-a792-deda1c4f809c
