language: php

php:
    - 7.0
    - 7.1

services:
    - postgresql
    - mysql

before_install:
     - mysql -e 'CREATE DATABASE IF NOT EXISTS notadd;'  
     - psql -c 'create database notadd;' -U postgres

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - travis_retry composer install --no-interaction --prefer-source

before_script:
    - git reset --hard HEAD

script:
    - php notadd integration:configuration --driver=mysql --host=127.0.0.1 --port=3306 --database=notadd --username=root --prefix=pre_
    - php notadd integration
    - vendor/bin/phpunit --verbose

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 4916eb3f-d129-4484-a792-deda1c4f809c

notifications:
    webhooks:
        - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
        - https://hook.bearychat.com/=bwA7K/travis/3c04d191a6066d3e178ab8d93643e708
